# Generated by Django 5.2.5 on 2025-08-27 13:37

import apps.jobs.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('apply_date', models.DateField()),
                ('valid_to', models.DateField()),
                ('portal', models.CharField(max_length=32, null=True)),
                ('link', models.URLField(max_length=128, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=32)),
                ('user', models.ManyToManyField(related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=64, null=True)),
                ('file_name', models.CharField(default='', max_length=128, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.jobs.utils.resume_file_path)),
                ('summary', models.TextField(null=True)),
                ('category', models.CharField(default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application_body', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('salary_range', models.CharField(max_length=32, null=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='jobs.jobapplication')),
                ('resume', models.ManyToManyField(blank=True, related_name='job_app_details', to='jobs.resume')),
            ],
        ),
    ]
