name: CI Pipeline

on: [push, pull_request]

env:
  SECRET_KEY: "django-insecure-u&+3c_-uwkww@=2q4h*)_0950xkn&jj80p*z@=5@hl+mwjrc$z"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.3.0
          # optionally:
          # pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 .

  unit-test:
    runs-on: ubuntu-22.04

    env:
      USE_SQLITE: True

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -m unit

  integration-test:
    runs-on: ubuntu-22.04

    env:
      DBHOST: "localhost"
      DBUSER: "postgres"
      DBNAME: "RecrAppDB"
      DBPORT: "5432"
      DBPASSWORD: "admin"

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ env.DBNAME }}
          POSTGRES_USER: ${{ env.DBUSER }}
          POSTGRES_PASSWORD: ${{ env.DBPASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run integration tests
        run: |
          pytest -m integration